### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [amyhsu-o/cloud-w01#1]
### git.md 
- 有用表格協助整理資料，這點做得很好
- 內容有自己的脈絡與整理，這也是很好的
- 提醒一下，現在的主分支應該不是 master 了？
- 另外「紀錄在 git repo 操作過程中，.git 檔案夾裡的變化，看看你可以觀察到什麼」這題會期望是有具體的觀察、紀錄與總結。

### video.md
有自己的反思是很好的事，透過 retro 去看見自己做得好跟可以更好的地方，好的維持、可以更好的改善，這樣就可以持續進步。

**Comment by amyhsu-o** [comment]
謝謝老師！
